### ISSUE TITLE
Export helpers seperately

### ISSUE THREAD

**Issue by antony** [helpers/handlebars-helpers#154]
Hapi has its own plugin registration mechanism - using these helpers requires me to circumvent that functionality, I'd rather just be able to import the helpers I need one by one, rather than have the library auto-register all the helpers in the world even though I'm only using one of them.

**Comment by jonschlinkert** [comment]
closing since this lib has been refactored. some of the helpers have also been externalized into separate libraries here on the [helpers org](https://github.com/helpers)
