### ISSUE TITLE
move to helpers org

### ISSUE THREAD

**Issue by jonschlinkert** [helpers/handlebars-helpers#178]
@doowb

When we move the next version to master, let's move this repo to `helpers/handlebars-helpers` and update ref links in the docs/metadata. just a reminder for us to do

**Comment by pburtchaell** [comment]
@jonschlinkert @doowb If you guys would like the help, I'd be open to joining that org to continue to watch PR's issues on this repo and help out where I can.

**Comment by jonschlinkert** [comment]
done! thanks for everything you're doing!

**Comment by tapsboy** [comment]
The helpers org has several standalone handlebars-helpers. Is there a plan to split up individual helper files from this repo into smaller separate repos?

**Comment by jonschlinkert** [comment]
The general thinking was has been that small, generic utility functions should stay in this lib. But more complex helpers probably belong in the org. 

Anyone is welcome to maintain helpers on the org. just let us know and someone will add you

**Comment by jonschlinkert** [comment]
done
