### ISSUE TITLE
Use it with Ember

### ISSUE THREAD

**Issue by hugocaillard** [helpers/handlebars-helpers#193]
Hello,

I know there's already a few issues about, but they are old and answered. Has anyone succeeded to make it work with Ember (1.13 or 2.0)?
I asked the question on [stackoverflow](https://stackoverflow.com/questions/32261023/ember-handlebars-layout-block-assemble-helpers-handlebars) as well.

**Comment by collegeimprovements** [comment]
I have the same question. :+1:  for this.

**Comment by TNAJanssen** [comment]
+1

**Comment by TangMonk** [comment]
+1

**Comment by Samushel** [comment]
Still no answer about this issue? Would be great to be able to use this helpers together with Ember.

**Comment by BenjaminHorn** [comment]
+1

**Comment by doowb** [comment]
Take a look at [this browserify example](https://github.com/doowb/handlebars-helpers-browserify-example).

You should be able to browserify `handlebars-helpers` during your build, then register helpers in your app through the same way you would register other helpers in ember. I'm not familiar with how to register helpers in ember but it shouldn't be different than registering directly with handlebars.

**Comment by jonschlinkert** [comment]
closing based on age, and since @doowb [answered the question](https://github.com/helpers/handlebars-helpers/issues/193#issuecomment-224704046)
