### ISSUE TITLE
for-in : o is not defined

### ISSUE THREAD

**Issue by devmark** [helpers/handlebars-helpers#246]
Please update to `for-in` to `~1.0.1`

**Comment by jonschlinkert** [comment]
Lol you must have literally downloaded this during the 30 seconds where that error occurred. It's not necessary. I immediately updated that library as I saw it as I was publishing (classic idiot move on my part).

anyway, this lib doesn't use 1.0 and can't be effect by that. No libraries depend on 1.0 yet as I just published it.

**Comment by devmark** [comment]
"for-in": "^0.1.6",
so what i download is 0.1.7 version which get the error. 

may could you change `^0.1.6` to `0.1.6` ?

**Comment by jonschlinkert** [comment]
clear out node_modules, and redownload everything. sorry, you would only be affected by this if you just downloaded when this happened. for-in is v0.1.8

**Comment by jonschlinkert** [comment]
sorry again

**Comment by devmark** [comment]
great. work now. Thanks @jonschlinkert

**Comment by jonschlinkert** [comment]
whew... thanks for the update! sorry again. Idk why I closed this before. In my brain I thought it was open still.... Well, now my brain will consider this closed lol.
