### ISSUE TITLE
Error: Cannot find module 'handlebars-helpers/lib/helpers/helpers-math' from '**my_project_path**'

### ISSUE THREAD

**Issue by gapsaras** [helpers/handlebars-helpers#252]
hey, I have a problem with using handlebars-helpers. After `npm install --save handlebar-helpers`,  I gulp to run my project, the error occured. But I didn't find a directory in  'handlebars-helpers/lib'.

**Comment by jonschlinkert** [comment]
sounds like a node error. try deleting node_modules and reinstall everything. If that doesn't work. you'll have to provide more detail (the gulp part isn't helpful, we just need to know the line of code where you're loading the helpers)

**Comment by gapsaras** [comment]
I just re-install the `handlebars-helpers` and it worked ! @jonschlinkert thanks for your tip.

**Comment by jonschlinkert** [comment]
no prob!
