### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by LaurentGoderre** [helpers/handlebars-helpers#255]
I started getting errors that `unless_eq` was not found, I looked up in the doc that it still exists and it did but in the code it's called `unlessEq` now it seems. Does the docs need updating?

**Comment by doowb** [comment]
This is documented in the readme [here](https://github.com/helpers/handlebars-helpers#unlesseq).
We're working on updating the assemble website to sync up the docs from different projects, but currently the site still has the old documentation.

**Comment by jonschlinkert** [comment]
> currently the site still has the old documentation.

right, the **assemble** site has the old docs, but this project is up-to-date. Closing based on that, and the outdated docs on assemble is already known and WIP, so no need to create another issue
