### ISSUE TITLE
error in webpack using in electron-vue

### ISSUE THREAD

**Issue by deboyblog** [helpers/handlebars-helpers#261]
I'm writing something to export file by custom template and using handlebars(success), But when I try to use this helpers it was error with
```
handlebars-helpers/lib/utils/utils.js
3:34-41 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by jonschlinkert** [comment]
hi @deboyblog this is a known bug in webpack, unrelated to this module. you can use [unlazy-loader](https://github.com/doowb/unlazy-loader) to work around it.

**Comment by deboyblog** [comment]
Thanks!
