### ISSUE TITLE
Helper suggestions: repeat and code

### ISSUE THREAD

**Issue by gakimball** [helpers/handlebars-helpers#264]
Hello there! I have two suggestions for fairly simple helpers. I'd be happy to put together a pull request if you're interested.

### Repeat

Repeats content `n` times. Useful for prototyping, when you need to fill out a page with a bunch of similar content.

```handlebars
<ul>
  {{#repeat 5}}
    <li>This is item {{@index}}.</li>
  {{/repeat}}
</ul>
```

### Code

Highlights an inline block of code. There's already `{{embed}}`, but this allows an inline sample to be highlighted.

```handlebars
{{#code 'js'}}
console.log('Hello.');
{{/code}}
```

**Comment by jonschlinkert** [comment]
hi @gakimball great ideas. maybe we can use https://github.com/helpers/handlebars-helper-repeat for the repeat helper? If the `code` helper adds highlighting, maybe should call that `highlight`? Or just add a highlight helper that can be used as a sub-expression with the `embed` helper?

**Comment by gakimball** [comment]
Ah didn't catch that there's already a `repeat` helper! How do you decide which helpers to include in this main repository and which ones to keep separate?

As for `highlight`, what would combining `embed` with a sub-expression look like?

**Comment by jonschlinkert** [comment]
> How do you decide which helpers to include in this main repository and which ones to keep separate?

since we don't collect any stats on usage, we try to get a sense for which helpers should be included based on a combination of issue history, questions (here, on assemble and stackoverflow), and also from some very meager google analytics stats from the assemble.io site. (we'll get better at this over time...)


> As for highlight, what would combining embed with a sub-expression look like?

I was wrong. I think you're `code` idea is good. Even though you already stated this, I was thinking embed already did at least the code part of the helper.

Maybe we should do both, `highlight` and `code`.

- `code` could add the code snippet 
- `highlight` could be used as a subexpression to add highlighting to the snippet

Does that make more sense?

**Comment by gakimball** [comment]
Re: `repeat`, I'll leave that up to you if you want to re-add it or not. This is a really nice all-in-one set of helpers for building static sites, and I think `repeat` is useful as a prototyping tool.

Re: `code`, could we only enable highlighting if the user passes a language string? So `{{#code}}` would give you a plain chunk of preformatted text, while `{{#code 'javascript'}}` would use JavaScript syntax highlighting. I've implemented a helper like this in other libraries, and in the past I had highlight.js auto-detect the language if the user didn't pass one to the helper. However, it's probably fine to require the user to be specific.

**Comment by jonschlinkert** [comment]
@gakimball I'd still prefer `highlight` over `code`. It's more explicit and it's the convention used by other template engines like liquid (you might have seen `{% highlight %}` tags used in Jekyll sites), and `code` does not necessarily imply highlighting. There are more potential use cases for a word that generic. 

If you're okay with using `highlight`, I'd be happy to take a pr for it, and/or `repeat`.

**Comment by jonschlinkert** [comment]
closing due to lack of response
