### ISSUE TITLE
Suggestion: strlen

### ISSUE THREAD

**Issue by why2pac** [helpers/handlebars-helpers#269]
`.strlen` is helper for getting the length of string.

I think it is essential helper but not exists. Is there any way to get string length with combines of helpers?

**Comment by doowb** [comment]
You can use the `length` helper:

```handlebars
{{length "mystring"}}
```

In a subexpression:

```handlebars
{{#gt (length "mystring") 5}}
  Too long!
{{/gt}}
```

Hope this helps.

**Comment by why2pac** [comment]
@doowb Thank you. But,

```node
{{length "my[string]"}}
```

Upper code is return 0.

It is because the `.length` helper try parse to object.

```node
if (typeof value === 'string' && /[[]/.test(value)) {
    value = utils.tryParse(value) || [];
  }
```

**Comment by why2pac** [comment]
This issue was closed, so I posted a new issue as a bug of `.length`.
