### ISSUE TITLE
String-related helpers return undefined for empty strings

### ISSUE THREAD

**Issue by xymbol** [helpers/handlebars-helpers#273]
A number of string-related helpers return `undefined` when passed empty strings:

- `capitalize`
- `capitalizeAll`
- `center`
- `ellipsis`
- `hyphenate`
- `isString`
- `lowercase`
- `pathcase`
- `plusify`
- `replace`
- `reverse`
- `sentence`
- `split`
- `titleize`
- `truncate`
- `uppercase`

The library uses this expression to validate string arguments:

```javascript
utils.isString = function(val) {
  return val && typeof val === 'string';
};
```

This returns `false` for empty strings even though they're valid strings. Usually, this is not an issue in a Handlebars template as `undefined` renders empty but, might be a problem if one is calling any of these helpers from other helpers.

I do understand that this might be intentional to skip string manipulation for empty strings and, that existing code could rely on these behavior but, interestingly, rectifying the above expression [does not break](https://travis-ci.org/helpers/handlebars-helpers/builds/236788374) any of the 419 tests.

I would propose changing the code or, docs and tests to make this explicit.

**Comment by jonschlinkert** [comment]
I mentioned that this would break code in the linked pr. Just because tests aren't breaking doesn't mean that downstream implementations won't break. 

Any subexpressions using these helpers that check for either a string or `undefined` will break.

**Comment by xymbol** [comment]
@jonschlinkert Thanks, again.

As I mentioned above, I am well aware that evaluating a helper that returns `undefined` renders empty in Handlebars.

That said, I find confusing that `html.truncate('', 100)` returns `undefined` instead of `''`. Then, if one wants to compose any of these helpers into new ones, things get more confusing. For example, a "summary" helper for post objects:

```javascript
const handlebars = require('handlebars');
const helpers = require('handlebars-helpers');
const html = helpers.html();

function description(post) {
  return html.ellipsis(post.body, 100);
}
function summary(post) {
  return '<p class="summary">' + description(post) + '</p>';
}

handlebars.registerHelper('description', description);
handlebars.registerHelper('summary', summary);
```

Now passing in an empty body, renders as:

```html
<p class="summary">undefined</p>
```

Our issues were somewhat related to this.

**Comment by jonschlinkert** [comment]
You are aware that it's `undefined` because of `post.body`, right?  It's not just undefined, it's an undefined property on an object. 

```js
var fn = handlebars.compile('<p class="summary">{{description post}}</p>');
console.log(fn());
//=> throws error "Cannot read property 'body' of undefined"

var fn = handlebars.compile('<p class="summary">{{description post}}</p>');
console.log(fn({post: ''}));
//=> '<p class="summary"></p>'
```
Change your custom helper to:

```js
function description(post) {
  return post ? html.ellipsis(post.body, 100) : '';
}

var fn = handlebars.compile('<p class="summary">{{description post}}</p>');
console.log(fn());
//=> '<p class="summary"></p>'
```

**Comment by xymbol** [comment]
>You are aware that it's undefined because of post.body, right? It's not just undefined, it's an undefined property on an object.

Yes, I am aware. With a defined property and an empty string value, it renders the `undefined` string because of the nested call and concatenation.

```javascript
const handlebars = require('handlebars');
const helpers = require('handlebars-helpers');
const html = helpers.html();

function description(post) {
  return html.ellipsis(post.body, 100);
}
function summary(post) {
  return '<p class="summary">' + description(post) + '</p>';
}

handlebars.registerHelper('description', description);
handlebars.registerHelper('summary', summary);

var fn = handlebars.compile('{{{summary post}}}');
console.log(
  fn({
    post: {
      body: ''
    }
  })
);
//=> <p class="summary">undefined</p>
```

>I would be fine with returning the given value instead of undefined if you want to update your pr to do only that.

Empty strings or any values? For which helpers?

**Comment by jonschlinkert** [comment]
> Empty strings or any values? 

Seems like we should consistently do:

```js
if (!utils.isString(str)) {
  return str;
}
```


> For which helpers?

Sorry, I'm confused. Were there two lists of helpers you wanted to update? I only saw one.

**Comment by xymbol** [comment]
>Seems like we should consistently do:

```javascript
  describe('isString', function() {
    it('should return true for string', function() {
      hbs.compile('{{isString "foo"}}')().should.equal('true');
    });

    it('should return true for empty string', function() {
      hbs.compile('{{isString ""}}')().should.equal('true');
    });

    it('should return false for number', function() {
      hbs.compile('{{isString 123}}')().should.equal('false');
    });

    it('should return false for null', function() {
      hbs.compile('{{isString null}}')().should.equal('false');
    });

    it('should return false when undefined', function() {
      hbs.compile('{{isString}}')().should.equal('false');
    });
  });
```

Are we okay with documenting this?

>Were there two lists of helpers you wanted to update?

I encountered this first with `ellipsis` and `truncate` but, going through the code noticed a number of similar cases. Ideally, they should all be consistent. Options:

1. String helpers return empty strings unmodified, `undefined` for non-strings
2. String helpers return non-strings and empty strings unmodified

I suspect 1) to be more backwards compatible and intuitive.

**Comment by jonschlinkert** [comment]
> Are we okay with documenting this?

Yes, that looks good to me, thanks.

> they should all be consistent

agreed, I think we should go with the first option as well. thanks

**Comment by jonschlinkert** [comment]
closed by the referenced pr

**Comment by Praveen245Kumar** [comment]
I want to return empty string (" ") llike this using handlebar is that possible??
