### ISSUE TITLE
String Filters For Output from YAML Not Working

### ISSUE THREAD

**Issue by grayghostvisuals** [helpers/handlebars-helpers#276]
I have this line where I spit out some categories…

```handlebars
{{#category "client"}}
    <li>{{ data.tags }} <a href="#{{data.title}}">{{data.title}}</a></li>
{{/category}}
```
Issue I'm running into is the fact I cannot [filter the output](https://github.com/helpers/handlebars-helpers#string) like so…

```handlebars
{{ capitalize data.tags }}
```
Here's the link to my current Gulp file [https://github.com/grayghostvisuals/site/blob/development/gulpfile.js](https://github.com/grayghostvisuals/site/blob/development/gulpfile.js)

**Comment by doowb** [comment]
@grayghostvisuals sorry for the delay...

What is `{{data.tags}}`? Will you log it out using `{{log data.tags}}` just before the `<li>` line. Then you can log out `{{log (capitalize data.tags)}}` to see what that returns.

**Comment by grayghostvisuals** [comment]
@doowb I have 2 sections on the same page both looping thru the same thing. Here they are in the order of appearance on my page and in the markup:

**First Loop**
```handlebars
{{#category "client"}}
	<li><a href="#{{lowercase data.title}}">{{data.title}}</a> : {{uppercase data.tags}}</li>
{{/category}}
```

**Second Loop**
```handlebars
{{#category "client"}}
<li id="{{lowercase data.title}}" class="ggv-datalist__item {{lowercase data.title}}">
	<a href="{{data.categories}}/{{lowercase data.title}}">
		<span class="ggv-datalist__item-data">{{uppercase data.tags}}</span>
	</a>
</li>
{{/category}}
```

The first and second loop's output is 100% correctly functioning, but only the second loop has the filter of "uppercase" applied using `{{uppercase data.tags}}`.

**Comment by doowb** [comment]
Will you post the resulting html snippets that are produced from rendering the templates?

Also... to see the values while the templates are rendering you can use the `{{log}}` helper:

```handlebars
{{#category "client"}}
<li id="{{lowercase data.title}}" class="ggv-datalist__item {{lowercase data.title}}">
	<a href="{{data.categories}}/{{lowercase data.title}}">
                {{log data.tags (uppercase data.tags)}}
		<span class="ggv-datalist__item-data">{{uppercase data.tags}}</span>
	</a>
</li>
{{/category}}
```

That will log the values to the console.

**Comment by doowb** [comment]
@grayghostvisuals I'm trying to reproduce the issue that you're having, but every place I add `{{uppercase data.tags}}` the rendered html has all uppercase characters there so I'm not sure where the issue is occurring without more information.

**Comment by grayghostvisuals** [comment]
@doowb Figured it out. Before I updated Assemble I was fixing it with CSS. Work as it should now. Thanks for checking.
