### ISSUE TITLE
{{first}} helper does not recognize array

### ISSUE THREAD

**Issue by bc-NikitaPuzanenko** [helpers/handlebars-helpers#277]
Using the provided example of `{{first "['a', 'b', 'c', 'd', 'e']" 2}}` returns `['`. Seems like its being interpreted as a string instead of an array.

Here is the code I am using based on the gulp example. Its possible I am missing something or Handlebars just does not like an inline array.

```
var $ = require('jquery');
var helpers = require('handlebars-helpers')({
  handlebars: Handlebars
});
$(function() {
      render();

  function render() {
    var tmpl = "<h2>{{first \"['a', 'b', 'c', 'd', 'e']\" 2}}</h2>";
    var fn = Handlebars.compile(tmpl);
    $('#content').html(fn);
  }
});
```

**Comment by doowb** [comment]
@bc-NikitaPuzanenko thanks for the issue. Handlebars does not support inline arrays, so you should pass in an array variable.

The example in the docs needs to be updated [here](https://github.com/helpers/handlebars-helpers/blob/master/lib/array.js#L137) to match the other array helper examples. I'll close this when the docs are updated.

**Comment by doowb** [comment]
Fixed the docs for these https://github.com/helpers/handlebars-helpers/commit/9a70c0be1e83c619bf0143eeda8c52eb2bf60d55
