### ISSUE TITLE
log-utils missing readline helper

### ISSUE THREAD

**Issue by mgurnani** [helpers/handlebars-helpers#284]
Hello,

I am using handlebars-helpers with webpack 2. I have loaded helpers in my JS like:
`var helpers = require('handlebars-helpers')();`

However when I try to build, it fails with the error:

ERROR in ./~/log-utils/index.js
Module not found: Error: Can't resolve 'readline' in '/Users/*****/node_modules/log-utils'

Is it a bug or am I missing something?

Thanks !

**Comment by jonschlinkert** [comment]
strange, I'm guessing you're using something like webpack, which doesn't use node.js require system?

**Comment by mgurnani** [comment]
Yes I mentioned I am using webpack 2. Also webpack does support RequireJS system. I have require ('xxxx') in many of my JS files and it works..
I was hoping to use the helpers library here but alas got into this issue. :(

**Comment by doowb** [comment]
`readline` is another built-in module like `fs` so you can add `readline: 'empty'` as another property. 

This is an issue with webpack if it's not finding built-in modules.

**Comment by doowb** [comment]
@mgurnani I'm going to close this since this isn't an issue with `handlebars-helpers`.

Try updating your webpack config with:

```js
node: {
  fs: 'empty',
  readline: 'empty'
}
```
