### ISSUE TITLE
CSS helper breaks external style links

### ISSUE THREAD

**Issue by jtsuyuki** [helpers/handlebars-helpers#292]
`{{{css "https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.8.0/github-markdown.css"}}}`

will return the HTML

`<link type="text/css" rel="stylesheet" href="https:/cdnjs.cloudflare.com/ajax/libs/github-markdown-css/2.8.0/github-markdown.css">`

the protocol has been changed from https:// to https:/ 

it looks like the lines in html.js are responsible

line#64
`    var fp = path.posix.join(assets, item);`

Probably should not be combining with the assets value anyway for external links.

**Comment by jonschlinkert** [comment]
> Probably should not be combining with the assets value anyway for external links.

Technically the `css` helper is for local assets. Perhaps that should either be clarified, or we should support your use case. To support your use case I recommend that we use `url.format()` instead of `path.join()`

**Comment by jtsuyuki** [comment]
created #293 to fix along with an additional test case for it.

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
