### ISSUE TITLE
Way to avoid names collision with object attributes or variable names

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [helpers/handlebars-helpers#295]
I have some collisions with the helpers names and object attributes. Eg: I've a model that has the 'default' attribute, but when I import the helpers, it broke my script because has a 'default' helper too. What's the best way to avoid it?

**Comment by jonschlinkert** [comment]
You can selectively register the helpers you need (as mentioned in the readme). But also make sure you register the helpers from `handlebars-helpers` first, then register your own helpers so they override the ones from this lib.
