### ISSUE TITLE
math.js - helpers.add bug

### ISSUE THREAD

**Issue by cocody** [helpers/handlebars-helpers#299]
# Source
handlebars-helpers/lib/utils/math.js/helpers.add 
`helpers.add = function(a, b) {
  return a + b;
};`

1 + 1 == 11

....

**Comment by doowb** [comment]
Hi @cocody, the [current source for add](https://github.com/helpers/handlebars-helpers/blob/master/lib/math.js#L31-L39) checks to see if the values are numbers then uses `Number(a) + Number(b)` to ensure number like strings are coerced into numbers before adding.

It doesn't look like you're using the latest version of `handlebars-helpers`. This should be fixed when you upgrade.

When you upgrade, if you're still having an issue, please post the code you use to register `handlebars-helpers`, the templates where `{{add}}` is used, and the data that is passed into the template when rendering.

I'm going to close this, but feel free to reopen if upgrading does fix your issue.

**Comment by cocody** [comment]
thanks your feedback, this solution is resolved when I upgrade.

**Comment by cocody** [comment]
but I think following the code is unnecessary in `Math.js`
is should be move into `String.js`
``` 
if (typeof a === 'string' && typeof b === 'string') {
    return a + b;
  }
```

**Comment by jonschlinkert** [comment]
> but I think following the code is unnecessary in Math.js

We can only have one `.add` helper, doesn't it make more sense for `add` to be used for math? There is also an [append helper](https://github.com/helpers/handlebars-helpers/blob/master/lib/string.js#L22) that does what you described.
