### ISSUE TITLE
Split string on line-break

### ISSUE THREAD

**Issue by rafegoldberg** [helpers/handlebars-helpers#300]
Have noticed a minor issue when trying to `{{split}}` a string by each line: 

```handlebars
{{log (split someMultiLineString "\n")}}
```

I'd assumed that I could use that escaped linefeed character like I would in pure Javascript, but alas — this doesn't give the expected result! (Instead it returns the _entire_ original string wrapped in an array...) Wondering if there's some type of workaround to reference line breaks? Or does it stem from something deeper in the way Handlebars parses these kinds of escaped chars?

In any case, love these helpers!

**Comment by doowb** [comment]
@rafegoldberg thanks for the issue. There might be something else going on with your setup that's causing either the `someMultiLineString` variable to not have any `"\n"` characters in it, or the `"\n"` character is being interpurrted as `"\\n"`.

I validated that this works with the following script:

```js
'use strict';
var Handlebars = require('handlebars');
var helpers = require('handlebars-helpers');

Handlebars.registerHelper(helpers());

var tmpl = '{{log (split str "\n")}}';
var fn = Handlebars.compile(tmpl);
var str = `this is
a multi-line string
created using a template string
`;

var str2 = [
  'this is',
  'a multi-line string',
  'created by joining an array'
].join('\n');

var str3 = 'this is\na multi-line string\ncreated by adding newlines';

fn({str: str});
fn({str: str2});
fn({str: str3});
```

If you have a similar script showing how you're reproducing the issue it might help to track it down and we can figure out if it's a bug someplace else.

**Comment by rafegoldberg** [comment]
thanks for the info @doowb; closing out this issue an take a closer look at my setup.

**Comment by kAleksei** [comment]
Faced with this issue. I use this extension in [Xplat Release Notes VSIX package](https://github.com/rfennell/AzurePipelines/releases/tag/XPlat-2.6.9).
```
{{log (split this.description "\n")}}
```
Log messages:
```json
[ 'Select only one item in the collection for appropriate semantic versioning:\n- [X] Major\n- [ ] Feature\n- [ ] Hotfix\n\n###Breaking changes\n - Some changes' ]
[ '# Breaking changes\n- Some changes added\n# Fixes\n- Something fixed' ]
```

**Comment by zkent** [comment]
Has anyone come up with a solution for this?  I am trying to use `split` for strings that have a double newline such as `\n\n`.  I can't figure out how to split them.  Where is the `split` helper coming from?  I haven't seen it in the code.
