### ISSUE TITLE
Helper to get current filename

### ISSUE THREAD

**Issue by HaoZeke** [helpers/handlebars-helpers#301]
So maybe something like

{{fname}} which should give the name.html of the **current** page?

**Comment by jonschlinkert** [comment]
https://github.com/helpers/handlebars-helpers/blob/master/lib/path.js#L81-L100?

**Comment by HaoZeke** [comment]
That assumes you can pass the full path...

**Comment by doowb** [comment]
@HaoZeke handlebars renders string templates so there isn't a way to know that the filename is. You'll need to pass that on the context to handlebars, then you can use the `path` helpers that Jon linked to.
