### ISSUE TITLE
How to combine array helpers with each loops ?

### ISSUE THREAD

**Issue by Mons-web** [helpers/handlebars-helpers#308]
Hi !
Thanks a lot for those very useful helpers :)

I'm wondering how can I combine array helpers with each loops.

For example:

**1) Sorting array before running the loop.**

I found a dirty way for this one, but I'm sure there is a cleaner solution.
What I currently do is commenting the sorting code like this:
```
<!-- {{sortBy pages "name"}} -->
{{#each pages}}
  <li>
      <a href="{{name}}.html">{{titleize name}}</a>
  </li>
{{/each}}
```
Obviously it's working, but I have some HTML comments output

**2) First N items of an array before running the loop**

I have an array with 10 items, I would like to display in the loops only the 3 first items.
I tried several things but none are working!
What I look for is something like:
```
{{#first pages 3}}
  <li>
      <a href="{{name}}.html">{{titleize name}}</a>
  </li>
{{/first}}
```
When I write this, I have this output:
`[object Object],[object Object],[object Object]`

Any help would be much appreciated :)
Thanks!

**Comment by doowb** [comment]
@Mons-web take a look at [handlebars subexpressions](http://handlebarsjs.com/expressions.html#subexpressions).

You should be able to do the following:

```handlebars
{{#each (sortBy pages "name")}}
{{/each}}

{{#each (first pages 3)}}
{{/each}}
```
