### ISSUE TITLE
Question about `is-even` package

### ISSUE THREAD

**Issue by semanser** [helpers/handlebars-helpers#315]
Referring to my pull request #314 , I want to say that I do not want to troll by no means. I really was interested to keep projects simple but useful. 

I have looked at the code, but still, do not understand why that package cannot be removed?

@jonschlinkert Sorry if you understand me incorrect.

**Comment by jonschlinkert** [comment]
What will happen on that line if a negative number is passed? What about a fraction?

**Comment by semanser** [comment]
Source: [Wolfram MathWorld](http://mathworld.wolfram.com/EvenNumber.html)

> An even number is an integer of the form n=2k, where k is an integer. The even numbers are therefore ..., -4, -2, 0, 2, 4, 6, 8, 10

So even negative numbers can be odd or even.
If you pass a fractional number everything will work as expected, I think.

**Comment by jonschlinkert** [comment]
```js
console.log('is-odd', 1.9999999999999998 % 2 === 0) // true
console.log('is-odd', 1.9999999999999999 % 2 === 0) // false
```

**Comment by semanser** [comment]
I think you mean:
```
console.log('is-odd', 1.9999999999999998 % 2 === 0) // **false**
console.log('is-odd', 1.9999999999999999 % 2 === 0) // **true**
```

But anyway, yes that's an interesting example. Thanks.

**Comment by jonschlinkert** [comment]
> I think you mean:

indeed, I retyped them. thanks for correcting.

> But anyway, yes that's an interesting example. Thanks.

This isn't unique, and it's not an extreme edge case. It's a floating point bug that commonly occurs in math operations, like with currency.

**Comment by aurelienbouteiller** [comment]
I've just seen that the is-even lib is still used in this project and i understand the security used in this lib can be usefull but i think we can really reduce it by just one line of code.

const isEven = (value) => Number.isSafeInteger((newValue = Number.parseInt(value))) && newValue % 2 === 0;

Tell me what you think ?

I've tried with some examples:
isEven(-10) //true
isEven(4/2) //true
isEven(9/3) //false
isEven(1000/0) //false
isEven("500") //true

**Comment by jonschlinkert** [comment]
@aurelienbouteiller please do a PR. thanks
