### ISSUE TITLE
Is there a need for creating helper for #if inside #each loop where checking is there something inside another collection?

### ISSUE THREAD

**Issue by shone83** [helpers/handlebars-helpers#318]
I try something like this:

```
<select name="electoralUnit" multiple class="form-control" id="exampleFormControlSelect2" size="40">
  {{#each electoralUnits}}
      <option value="{{id}}" {{#if stateResult.electoralUnit}} disabled {{/if}}>{{name}}</option>
  {{/each}}
</select>
```

where stateResult is a collection outside electoralUnit collection. So, I have a multiple select with electoralUnits and I need to check if one of electoralUnits is in stateResult (already made it ref so ObjectId is in there) then that electoralUnit suppose to be disabled. I try to use ../stateResult in if helper but that's not working. Any helpe with this?

**Comment by doowb** [comment]
@shone83 you should try asking this on StackOverflow and posting some additional information (like what your data object looks like). The `{{each}}` and `{{if}}` helpers are built into handlebars so I'm not sure how we can help in this repository. If you're using helpers from this project and you run into a bug, please feel free to open another issue.

**Comment by shone83** [comment]
I tried there too, but nothing:
https://stackoverflow.com/questions/49417226/handlebars-disable-attribute-if-id-exist

**Comment by jonschlinkert** [comment]
Hi @shone83, try using the `{{log .}}` helper to see the context and available properties.

**Comment by shone83** [comment]
When I use log nothing happens...

**Comment by shone83** [comment]
Hi @jonschlinkert when I use log nothing happens...

**Comment by doowb** [comment]
@shone83 I'll post an answer on stackoverflow if one isn't there yet. Thanks for posting the link to it.

**Comment by shone83** [comment]
@doowb that would be great, still nothing yet ;)
