### ISSUE TITLE
Is there a way to pass custom helpers?

### ISSUE THREAD

**Issue by dev2games** [helpers/handlebars-helpers#322]
I have my own module, and wish to use this library. Is there a way to export my modules into this one? So for example. 

```
var helpers = require('./helpers');
helpers: require('handlebars-helpers')({
        customHelpers: helpers
        }
    }),
```

I am using Sails JS.

**Comment by doowb** [comment]
That shouldn't be necessary. You can either extend the object returned from `handlebars-helpers` or use syntax that Sails provides (I'm not familiar with Sails).

```js
const customHelpers = require('./helpers');
let helpers = require('handlebars-helpers')();

// add them as a property
helpers.customHelpers = customhelpers;

// or extend the helpers object
Object.assign(helpers, customHelpers);
```
I hope this helps.

**Comment by dev2games** [comment]
@doowb Incredibly helpful, thank you!
