### ISSUE TITLE
pick

### ISSUE THREAD

**Issue by jw-miaem** [helpers/handlebars-helpers#326]
Hi, I cant seem to get pick to work with array of values. This is what I'm trying and possibly have incorrect format:
{{#pick ['progressTitle','pageTitle'] health.signup.company-registration}}

**Comment by doowb** [comment]
Handlesbars doesn't accept literal array syntax in the templates, so you'll need to put the array of properties on the data context, then pass that variable in:

```js
const data = {
  props: ['progressTitle', 'pageTitle'],
  health: {
    signup: {
      company-registration: {
        progressTitle: 'Foo',
        pageTitle: 'Page foo'
      }
    }
  }
};

Handlebars.compile('{{#pick props health.signup.company-registration}}{{/pick}}')(data);
```

I hope this helps.

**Comment by jw-miaem** [comment]
Thanks for help
