### ISSUE TITLE
Replacing Swag with handlebars-helpers

### ISSUE THREAD

**Issue by karlitos** [helpers/handlebars-helpers#358]
I'd like to migrate from the [Swag](https://github.com/elving/swag) library to handlebar helpers, since Swag is unmaintained and depends ob old and vunnerable version of Handlebars. My app depends on Handlebars and HandlebarsAsync and I use Swag like this:
```javascript
const promisedHandlebars = require('promised-handlebars');
const HandlebarsAsync = promisedHandlebars(require('handlebars'));
const Handlebars = require('handlebars');
const Swag = require('swag');

...

// Register swag handlebars helpers
Swag.registerHelpers(HandlebarsAsync);
Swag.registerHelpers(Handlebars);
```

How should it look like with handlebars-helpers ?

**Comment by doowb** [comment]
See the [Optionally pass your own handlebars](https://github.com/helpers/handlebars-helpers#usage) section under `Usage`.

```js
const helpers = require('handlebars-helpers');
helpers({ handlebars: HandlebarsAsync });
helpers({ handlebars: Handlebars });
```

The return value from the `helpers` function above is just the object of registered helpers on the `Handlebars` instance that you passed in. I'm not sure how `promised-handlebars` works, so you might run into issues that don't have anything to do with this library (`handlebars-helpers`).

**Comment by karlitos** [comment]
Many thanks I will give it a try.
