### ISSUE TITLE
How to integrate with Ghost CMS

### ISSUE THREAD

**Issue by rdehuyss** [helpers/handlebars-helpers#364]
Hi,

I would love some documentation on how to use this with Ghost CMS... 

The installation itself isn't enough (or I did something wrong)

Thanks,
Ronald

**Comment by doowb** [comment]
Hi @rdehuyss 

Do you have any code that you've tried, that you could show?

Personally, I have not tried to integrate this package with Ghost and I don't know what the steps are for adding helpers to Ghost. If you have a link to the Ghost documentation on adding helpers, it might help someone here create the documentation you're looking for.

**Comment by rdehuyss** [comment]
I did not found a lot of documentation for that either - [this](https://dotnetfalcon.com/stackoverflow-adventures-creating-custom-ghost-helpers-using-apps/) is what I tried but it did not work with me.

The post is also 2 years old already so I don't know if it is still relevant...

**Comment by doowb** [comment]
Thanks for the additional information. I looked through the Ghost docs and searched their issues. The most recent information indicates that Ghost stopped supporting custom helpers and that you can only use the helpers that Ghost provides.

I'm going to close this issue, but if you find out more information, please let us know.

**Comment by rdehuyss** [comment]
Could you then what remove it (ghost) from your description as this was what me got over here in the first place?

Thanks
