### ISSUE TITLE
can you split a string with a delimiter and loop through and display with breaks?

### ISSUE THREAD

**Issue by cpluceDev** [helpers/handlebars-helpers#371]
i have a string with a pipe or semicolon delimiter.  Can i split this up and create an array than do a for each to display the values with a break or return carriage for each line? i know i can use the split function which gets me the index positions and a for each  

thx

**Comment by doowb** [comment]
```handlebars
{{#each (split str "|") as |val|}}
  {{val}}<br />
{{/each}}
```

This should work? Have you tried it?

**Comment by cpluceDev** [comment]
thx
