### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by acotty** [helpers/handlebars-helpers#382]
Hello, is this repo still maintained...? Last commit was 18 Nov 2017 and very few comments on issues or PR's since then... 😒

If this is not maintained is there a fork that someone is maintaining? If not is there another handlebar helpers package that can replace this one that is maintained.

The reason is that I would like to use a package that it maintained.

**Comment by ivankozlovcodes** [comment]
Bump. I am wondering the same thing.

**Comment by jonschlinkert** [comment]
Please read this: https://github.com/jonschlinkert/idiomatic-contributing#code-of-conduct-and-beyond

Closing since there will never be a time when I answer this question, or view the question as anything but trolling.
