### ISSUE TITLE
Generating a navigation with dynamic active class

### ISSUE THREAD

**Issue by ahmedelgabri** [helpers/handlebars-helpers#52]
I'm trying to generate a navigation with a dynamic active class & here is my YAML & Handelbars

`config.yaml`

```

---
mainnav:
- home
- about us
- contact

---
```

`menu.hbs` partial

```
{{#config.mainnav}}
      <li><a {{#is page.basename this}} class="is-current" {{/is}} href="{{hyphenate this}}.html">{{capitalizeEach this}}</a></li>
{{/config.mainnav}}
```

everything is working but the active class, it doesn't get applied at all.

**Comment by grayghostvisuals** [comment]
By chance is there a way to do this for gulp? The isActive helper does not work for me nor do the methods above.
